spring.application.name=notification-service
server.port=${SERVER_PORT:3006}

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/ezzewash_notification}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:1234}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=${JWT_SECRET:cff4f80b6d0d6a86422b0398ecc5eb9a68f6661b1225c0c0394ccccf2847544704e7849ef92ef434a055230fb55663186f91ddec02966310293c42fcbdf95992}

auth-service.url=${AUTH_SERVICE_URL:http://localhost:3001}

spring.mail.host=${MAIL_HOST:smtp.gmail.com}
spring.mail.port=${MAIL_PORT:587}
spring.mail.username=abdulaowalasif2001@gmail.com
spring.mail.password=eomquqxigokefyfx
mail.from=abdulaowalasif2001@gmail.com
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000
