spring.application.name=rider-service
server.port=${SERVER_PORT:3004}

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/ezzewash_rider}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:1234}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true

spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}

jwt.access-secret=${JWT_ACCESS_SECRET:cff4f80b6d0d6a86422b0398ecc5eb9a68f6661b1225c0c0394ccccf2847544704e7849ef92ef434a055230fb55663186f91ddec02966310293c42fcbdf95992}

catalog-service.url=${CATALOG_SERVICE_URL:http://localhost:3002}
rider.assignment.fixed-earning=${RIDER_FIXED_EARNING:150.00}
order-service.url=${ORDER_SERVICE_URL:http://localhost:3003}